'use strict';
const test=require('node:test'),assert=require('node:assert/strict'),fs=require('node:fs'),vm=require('node:vm'),path=require('node:path');
const source=fs.readFileSync(path.join(__dirname,'../resources/js/main.js'),'utf8');
const helpers=require('../resources/js/config-helpers.js');
function app(){const elements=new Map();const context=vm.createContext({console,Map,Set,Date,Promise,JSON,Math,Array,Object,URL,AbortController,TextEncoder,performance,setTimeout,clearTimeout,window:{__SMART_PROXY_TEST__:true},SmartProxyConfig:helpers,document:{getElementById:id=>{if(!elements.has(id))elements.set(id,{textContent:'',innerHTML:'',className:'',value:'',style:{},dataset:{},attrs:{},focus(){},setAttribute(k,v){this.attrs[k]=v},classList:{toggle(){}}});return elements.get(id)}}});vm.runInContext(source,context);return {api:context.window.SmartProxyLifecycleTest,elements,context};}
const entry=(key,node='香港 02')=>({key,node,tag:key,subscriptionId:'a',subscriptionName:'A'});
const result=()=>({metricKind:'stream-quality-v1',measurement:'sse-and-download',status:'done',ok:true,download:{ok:true,mbps:18},profileKey:'sse-fixture',measuredAt:1789516800000,verified:true,sampleCount:3,successfulSamples:3,stream:{ok:true,flowPass:true,jitterMs:7.4,firstSampleMs:125,maxExtraGapMs:18,burstRatio:0}});
function fill(a){const s=a.api.state;s.subscriptionNodeCatalog=[entry('one'),entry('two','日本 01')];s.currentNode='one';s.nodeCodexResults.set('one',result());s.settings={...s.settings,subscriptions:[{id:'a',name:'A'}],networkProbeStore:{one:{status:'done',delayMs:0}}};return s;}
test('ATELIER empty state never invents region, latency or successful stream measurements',()=>{const a=app(),v=a.api.atelierSummary(a.api.state);assert.equal(v.node,'尚未选择节点');assert.equal(v.region,'准备连接');assert.equal(v.jitter,'—');assert.equal(v.qualityState,'未测试');assert.equal(v.count,0);});
test('ATELIER reads only selected node; numeric zero is valid; render has no state mutation',()=>{const a=app(),s=fill(a);const before=JSON.stringify(s);let v=a.api.atelierSummary(s);assert.equal(v.region,'Hong Kong');assert.equal(v.jitter,'7');assert.equal(v.latency,'0 ms');a.api.renderAtelierOverview();assert.equal(a.elements.get('atelierDetailFirst').textContent,'125 ms');assert.equal(JSON.stringify(s),before);s.currentNode='two';v=a.api.atelierSummary(s);assert.equal(v.region,'Japan');assert.equal(v.jitter,'—');assert.equal(v.qualityState,'未测试');});
test('ATELIER explicitly labels previous successful scores on failure, cancellation and pending probes',()=>{const a=app(),s=fill(a);for(const status of ['error','cancelled']){s.nodeCodexResults.get('one').lastAttempt={status};const v=a.api.atelierSummary(s);assert.match(v.qualityState,/历史/);assert.match(v.qualityMeta,/上次成功/);assert.equal(v.jitter,'7');}s.codexProbePendingKeys.add('one');assert.equal(a.api.atelierSummary(s).qualityState,'测试中 · 历史');});
test('ATELIER rejects malformed, failed and legacy model results instead of showing false flow success',()=>{const a=app(),s=fill(a);for(const value of [{...result(),ok:false},{...result(),stream:{...result().stream,jitterMs:null}},{...result(),stream:{...result().stream,jitterMs:NaN}},{status:'done',tokPerSec:99}]){s.nodeCodexResults.set('one',value);assert.equal(a.api.atelierSummary(s).jitter,'—');assert.equal(a.api.atelierSummary(s).qualityState,'未测试');}});
test('ATELIER subscription membership counts shared nodes once per source and escapes names',()=>{const a=app(),s=fill(a);s.settings.subscriptions=[{id:'a',name:'<img src=x onerror=alert(1)>'},{id:'b',name:'B'}];s.subscriptionNodeCatalog=[{...entry('one'),subscriptionIds:['a','b','a']}];const v=a.api.atelierSummary(s);assert.equal(v.count,1);assert.deepEqual(Array.from(v.sources,x=>x.count),[1,1]);a.api.renderAtelierOverview();assert.doesNotMatch(a.elements.get('atelierSources').innerHTML,/<img/);assert.match(a.elements.get('atelierSources').innerHTML,/&lt;img/);});
test('ATELIER historical network delay is not presented as a new success',()=>{const a=app(),s=fill(a);s.settings.networkProbeStore.one={status:'error',lastSuccess:{delayMs:231}};assert.equal(a.api.atelierSummary(s).latency,'231 ms · 历史');s.settings.networkProbeStore.one={status:'done',delayMs:null};assert.equal(a.api.atelierSummary(s).latency,'—');});
test('ATELIER preserves seven views and explicit node action delegation with keyboard selection',()=>{const html=fs.readFileSync(path.join(__dirname,'../resources/index.html'),'utf8');assert.equal((html.match(/class="view(?: active)?"/g)||[]).length,7);for(const id of ['toggleCoreBtn','testNetworkBtn','testAllCodexBtn','nodeGroups','systemProxyEnabled','globalProxyEnabled','homeSubscriptionUrl','saveSettingsBtn'])assert.ok(html.includes(`id="${id}"`),id);assert.match(source,/event\.target\.matches\("\[data-select-node\]"\)/);assert.match(source,/aria-pressed="\$\{!!\(current \|\| prepared\)\}"/);assert.doesNotMatch(source,/<div tabindex="0" role="button"[^`]*<button/);assert.match(source,/data-codex-probe-key/);assert.doesNotMatch(html,/网络延迟与模型速度分开/);assert.ok(html.indexOf('id="nodeGroups"')<html.indexOf('<details class="model-options'),'DOM keyboard order follows the node-first visual layout');});
test('ATELIER pending network results are explicitly historical, not fresh success',()=>{const a=app(),s=fill(a);s.networkPendingKeys.add('one');assert.equal(a.api.atelierSummary(s).latency,'0 ms · 历史 / 测试中');s.settings.networkProbeStore.one={status:'error',lastSuccess:{delayMs:23}};assert.equal(a.api.atelierSummary(s).latency,'23 ms · 历史 / 测试中');s.nodeCodexResults.set('one',{status:'error'});assert.equal(a.api.atelierSummary(s).qualityTone,'warning');assert.equal(a.api.atelierSummary(s).qualityState,'本次未通过');assert.match(a.api.atelierSummary(s).qualityMeta,/未取得有效成绩/);});
test('ATELIER core presentation distinguishes stopped, starting, running and stopping',()=>{const {api}=app();for(const [input,title,busy] of [[{},'代理未启动',false],[{mainStartPromise:{}},'正在启动代理…',true],[{mainProcess:{},mainCoreReady:true},'代理运行中',false],[{mainProcess:{},mainCoreReady:true,coreActionPending:'stopping'},'正在停止代理…',true]]){const p=api.corePresentation(input);assert.equal(p.title,title);assert.equal(p.busy,busy);}});
test('ATELIER core action disables duplicates, reports failure inline and preserves runtime ownership',async()=>{const a=app(),s=fill(a);vm.runInContext(`log=()=>{}; startMainCore=async()=>{window.starts=(window.starts||0)+1;await new Promise(r=>window.release=r);throw Error('fixture unavailable')};`,a.context);const pending=a.api.toggleCoreFromUI();assert.equal(a.elements.get('toggleCoreBtn').disabled,true);assert.equal(a.elements.get('toggleCoreBtn').attrs['aria-busy'],'true');await a.api.toggleCoreFromUI();assert.equal(a.context.window.starts,1);a.context.window.release();await pending;assert.equal(a.elements.get('toggleCoreBtn').disabled,false);assert.equal(a.elements.get('coreActionError').hidden,false);assert.match(a.elements.get('coreActionError').textContent,/fixture unavailable/);s.mainProcess={pid:123};s.mainCoreReady=true;vm.runInContext(`stopMainCore=async()=>{throw Error('fixture stop refused')};`,a.context);await a.api.toggleCoreFromUI();assert.equal(s.mainProcess.pid,123);assert.equal(s.mainCoreReady,true);});
test('ATELIER filtering does not shrink whole-test scope or cost estimates; clear restores list',()=>{const a=app(),s=fill(a);s.currentView='proxy-nodes';s.lastProbeRoundId='test-round';Object.assign(s.nodeCodexResults.get('one'),{roundId:'test-round',successRate:1});a.api.renderProxyNodes();const cost=a.elements.get('nodeScoreSummary').textContent;assert.match(cost,/本轮流式复测达标/);a.elements.get('nodeSearch').value='missing';a.api.renderProxyNodes();assert.equal(a.elements.get('nodeListCount').textContent,'显示 0 / 2 个节点');assert.equal(a.elements.get('nodeScoreSummary').textContent,cost);assert.equal(a.elements.get('testNetworkBtn').disabled,false);assert.match(a.elements.get('nodeGroups').innerHTML,/data-node-empty-action="clear"/);vm.runInContext('clearNodeFilter()',a.context);assert.equal(a.elements.get('nodeListCount').textContent,'2 个缓存节点');assert.equal(a.elements.get('clearNodeFilterBtn').hidden,true);});
test('ATELIER node rerender restores keyboard focus by stable action and node key',()=>{const a=app(),s=fill(a);s.currentView='proxy-nodes';a.api.renderProxyNodes();const box=a.elements.get('nodeGroups');let restored=false;box.contains=()=>true;box.querySelectorAll=()=>[{getAttribute:()=> 'two',focus(options){restored=options.preventScroll}}];a.context.document.activeElement={hasAttribute:name=>name==='data-node-key',getAttribute:()=> 'two'};a.api.renderProxyNodes();assert.equal(restored,true);});
test('ATELIER empty catalog offers subscription recovery and disables impossible bulk tests',()=>{const a=app();a.api.state.currentView='proxy-nodes';a.api.renderProxyNodes();assert.equal(a.elements.get('testNetworkBtn').disabled,true);assert.equal(a.elements.get('testAllCodexBtn').disabled,true);assert.match(a.elements.get('nodeGroups').innerHTML,/data-node-empty-action="subscriptions"/);assert.equal(a.elements.get('homeChooseNode').dataset.view,'subscriptions');});
test('ATELIER offline layout includes keyboard focus, reduced-motion, high contrast and responsive rules',()=>{const css=fs.readFileSync(path.join(__dirname,'../resources/styles.css'),'utf8');for(const pattern of [/prefers-reduced-motion/,/forced-colors/,/:focus-visible/,/max-width:760px/,/max-width:1120px/,/--bg:#f4f1eb/])assert.match(css,pattern);assert.doesNotMatch(css,/@import|https?:\/\//);});
